name: pytest_test_settings

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: List repository contents
      run: |
        pwd
        ls -R
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r binder/requirements.txt
        bash binder/postBuild
    - name: Run improved script with conftest.py and run tests with pytest
      run: pytest -v tests/test_no_changes_introduced_to_results.py
