name: pytest_test_settings

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r binder/requirements.txt
    - name: Check input file
      run: |
        ls -l Example_data/Results/Structure.str
        cat Example_data/Results/Structure.str | head -n 5
    - name: Display postBuild script contents
      run: cat binder/postBuild
    - name: Run postBuild script
      run: |
        pwd
        ls -l Example_data/Results/
        bash -x binder/postBuild
      working-directory: ${{ github.workspace }}
    - name: Check output file
      run: |
        ls -l Example_data/Results/EXPECTED_in_July2024_Structure.str
        cat Example_data/Results/EXPECTED_in_July2024_Structure.str | head -n 5
    - name: Run improved script with conftest.py and run tests with pytest
      run: pytest -v tests/test_no_changes_introduced_to_results.py
